language: node_js
node_js:
 - "node"
 
script: echo "Running tests against $(node -v) ... branch: $TRAVIS_BRANCH"

jobs:
  include:
    - stage: npm build and test
      script: yarn lint && yarn test && yarn generate
